//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystemTimologio.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.CategoryInvoices = new HashSet<CategoryInvoice>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int StationId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryInvoice> CategoryInvoices { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Station Station { get; set; }
        public virtual User User { get; set; }
    }
}
