//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystemTimologio.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public int InvoiceAdd { get; set; }
        public int InvoiceManage { get; set; }
        public int InventoryManage { get; set; }
        public int CategoryManage { get; set; }
        public int StationManage { get; set; }
        public int OperationManage { get; set; }
        public int UserManage { get; set; }
        public int PermissionMange { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
